### ISSUE TITLE
Repo name sometimes contains organisation name

### ISSUE THREAD

**Issue by Jamian** [Jamian/releasy#2] opened 2022-07-26 10:32 UTC
For some reason some responses for the name will contain the Org in the Repo name. For example `Jamian/releasy` instead of just `releasy`.

**Comment by stefangrosaru** [comment] 2022-08-01 20:35
Looked into this and it seems that the issue is caused by the Jira API returning inconsistent repo names which sometimes contain the org name as well.

Added a fix for this issue in my pull request #1.

The fix is checking if there is a slash in the repo name and then removing everything before it:
`repo_name = repo['name'] if '/' not in repo['name'] else repo['name'].split('/')[1]`

**Closed as completed** 2022-08-03 08:59 UTC
Labels: bug
